stages:
  prepare_database:
    cmd: python prepare_database.py
    deps:
    - vocabularies
    - prepare_database.py
    outs:
    - omop.db

  prepare_datasets:
    cmd: python prepare_datasets.py
    deps:
    - prepare_datasets.py
    - omop.db
    - sql_commands.yaml
    outs:
    - datasets/non_std_concept_synonym_to_std_vocab_code.csv
    - datasets/non_std_concept_to_std_vocab_code.csv
    - datasets/std_concept_synonym_to_std_vocab_code.csv
    - datasets/std_concept_to_std_vocab_code.csv

  split_datasets:
    cmd: python split_datasets.py
    deps:
    - split_datasets.py
    - datasets/non_std_concept_synonym_to_std_vocab_code.csv
    - datasets/non_std_concept_to_std_vocab_code.csv
    - datasets/std_concept_synonym_to_std_vocab_code.csv
    - datasets/std_concept_to_std_vocab_code.csv
    outs:
    - datasets/splits

  # Llama 3.2 1B JEPA experiments
  llama-32-1b-jepa__tokenize_datasets:
    cmd: python tokenize_datasets.py --params 
      experiments/llama-32-1b-jepa/params.yaml
    deps:
    - tokenize_datasets.py
    - datasets/splits
    - experiments/llama-32-1b-jepa/params.yaml
    outs:
    - datasets/splits-tokenized

  llama-32-1b-jepa__train:
    cmd: python train.py --params experiments/llama-32-1b-jepa/params.yaml
    deps:
    - train.py
    - datasets/splits-tokenized
    - experiments/llama-32-1b-jepa/params.yaml
    outs:
    - experiments/llama-32-1b-jepa/outputs