stages:
  prepare_database:
    cmd: python prepare_database.py
    deps:
    - vocabularies
    - prepare_database.py
    outs:
    - omop.db

  prepare_datasets:
    cmd: python prepare_datasets.py
    deps:
    - prepare_datasets.py
    - omop.db
    - sql_commands.yaml
    outs:
    - datasets/standard_concept.csv
    - datasets/standard_concept_synonym.csv
    - datasets/mapped_non_standard_concept.csv
    - datasets/mapped_non_standard_concept_synonym.csv

  prepare_vector_database:
    cmd: python prepare_vector_database.py
    deps:
    - prepare_vector_database.py
    - datasets/standard_concept.csv
    - datasets/standard_concept_synonym.csv
    - datasets/mapped_non_standard_concept.csv
    - datasets/mapped_non_standard_concept_synonym.csv
    outs:
    - chroma/