site_name: Any-to-Any Terminology Mapping
site_url: 
repo_url: https://github.com/precisiondata/aatm
site_description: Any-to-Any Terminology Mapping, a tool for mapping between different terminologies in the healthcare domain.
site_author: Vinicius Anjos de Almeida (https://github.com/almeidava93) supported by Precision Data.

nav:
  - Home: 'index.md'
  - Getting Started: 
    - 'getting-started/index.md'
    - Installation: 'getting-started/installation.md'
    - Environment variables: 'getting-started/env.md'
    - Project artifacts created locally: 'getting-started/artifacts.md'
    - Basic concepts: 'getting-started/concepts.md'
    - Quick start:
      - Command Line Interface: 'getting-started/quick_start_cli.md'
      - Python API: 'getting-started/quick_start_python_api.md'
  - API Reference:
    - Command Line Interface: 'reference/cli.md'
    - Pipeline components:
      - Pipeline: 'reference/pipeline.md'
      - Translators: 'reference/translators.md'
      - Embedding functions: 'reference/embedding_functions.md'
      - Retrievers: 'reference/retrievers.md'
      - Rerankers: 'reference/rerankers.md'
      - Selectors: 'reference/selectors.md'
      - Terminology mapper: 'reference/terminology_mapper.md'
    - User interface:
      - Search engine interface: 'reference/search_ui.md'
    - Registries:
      - Rerankers registry: 'reference/registries/rerankers.md'
      - Retrievers registry: 'reference/registries/retrievers.md'
      - Selectors registry: 'reference/registries/selectors.md'
      - Translators registry: 'reference/registries/translators.md'
    - Other modules:
      - Data Models: 'reference/data_models.md'
      - Debug: 'reference/debug.md'
      - Local database utilities: 'reference/local_database_utils.md'
      - Logs: 'reference/logs.md'
      - Prompt helpers: 'reference/prompt_helpers.md'



theme:
  name: material
  locale: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes 
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link

extra:
  version: 0.1.0

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [aatm]
          options:
            docstring_style: google
            show_source: true
            members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower